version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
    - 3.4.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.15
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.1
    - 7.23.2
  - dependency-name: "@hckrnews/validator"
    versions:
    - 4.0.0
  - dependency-name: eslint-plugin-html
    versions:
    - 6.1.1
    - 6.1.2
  - dependency-name: jscpd
    versions:
    - 3.3.23
    - 3.3.24
    - 3.3.25
  - dependency-name: prismjs
    versions:
    - 1.23.0
  - dependency-name: ini
    versions:
    - 1.3.7
  - dependency-name: jest
    versions:
    - 26.6.3
  - dependency-name: eslint-plugin-jsx-a11y
    versions:
    - 6.4.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: coveralls
    versions:
    - 3.1.0
  - dependency-name: node-fetch
    versions:
    - 2.6.1
